"""adiciona tabela de questionarios

Revision ID: 2ab18391a8a0
Revises: c3e9d4a7f1b2
Create Date: 2026-09-15 23:56:41.252437

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "2ab18391a8a0"
down_revision: str | None = "c3e9d4a7f1b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questionarios",
        sa.Column("versao", sa.String(length=50), nullable=False),
        sa.Column("perguntas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("versao"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("questionarios")
    # ### end Alembic commands ###
