"""adiciona anamnese_id e erro em diagnosticos, parametros_captura em imagens

Revision ID: 594b04654498
Revises: b4c99c48b0f2
Create Date: 2026-09-11 22:03:31.435348

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "594b04654498"
down_revision: str | None = "b4c99c48b0f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("diagnosticos", sa.Column("anamnese_id", sa.Integer(), nullable=False))
    op.add_column("diagnosticos", sa.Column("erro", sa.Text(), nullable=True))
    op.alter_column("diagnosticos", "classificacao_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("diagnosticos", "escala_saburra", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "diagnosticos",
        "confianca_ia",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.create_unique_constraint(None, "diagnosticos", ["anamnese_id"])
    op.create_foreign_key(
        None, "diagnosticos", "anamneses", ["anamnese_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "imagens",
        sa.Column("parametros_captura", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("imagens", "parametros_captura")
    op.drop_constraint(None, "diagnosticos", type_="foreignkey")
    op.drop_constraint(None, "diagnosticos", type_="unique")
    op.alter_column(
        "diagnosticos",
        "confianca_ia",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column("diagnosticos", "escala_saburra", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("diagnosticos", "classificacao_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("diagnosticos", "erro")
    op.drop_column("diagnosticos", "anamnese_id")
    # ### end Alembic commands ###
