"""cria tabela anamneses

Revision ID: 652cbc54920d
Revises: 65cb67e51405
Create Date: 2026-09-10 11:32:14.618561

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "652cbc54920d"
down_revision: str | None = "65cb67e51405"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anamneses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paciente_id", sa.Integer(), nullable=False),
        sa.Column(
            "data_preenchimento",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("respostas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["paciente_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("anamneses")
    # ### end Alembic commands ###
