"""cria tabelas iniciais

Revision ID: 65cb67e51405
Revises:
Create Date: 2026-09-04 20:46:06.681207

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "65cb67e51405"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classificacoes_diagnostico",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("nome_exibicao", sa.String(length=100), nullable=False),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_classificacoes_diagnostico_codigo"),
        "classificacoes_diagnostico",
        ["codigo"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "conteudos_diagnostico",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("classificacao_id", sa.Integer(), nullable=True),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("dados", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["classificacao_id"],
            ["classificacoes_diagnostico.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "diagnosticos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paciente_id", sa.Integer(), nullable=False),
        sa.Column("classificacao_id", sa.Integer(), nullable=False),
        sa.Column("escala_saburra", sa.Integer(), nullable=False),
        sa.Column("confianca_ia", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "data_diagnostico",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("profissional_revisor_id", sa.Integer(), nullable=True),
        sa.Column("data_revisao", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observacoes_revisao", sa.Text(), nullable=True),
        sa.Column("interesse_consulta", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["classificacao_id"],
            ["classificacoes_diagnostico.id"],
        ),
        sa.ForeignKeyConstraint(["paciente_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["profissional_revisor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "profissionais",
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("registro_profissional", sa.String(length=50), nullable=True),
        sa.Column("especialidade", sa.String(length=100), nullable=True),
        sa.Column("vinculado_hality", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["usuario_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("usuario_id"),
    )
    op.create_table(
        "imagens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("diagnostico_id", sa.Integer(), nullable=False),
        sa.Column("url_arquivo", sa.String(length=500), nullable=False),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.Column(
            "data_captura",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["diagnostico_id"], ["diagnosticos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pacientes_profissionais",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paciente_id", sa.Integer(), nullable=False),
        sa.Column("profissional_id", sa.Integer(), nullable=False),
        sa.Column(
            "data_vinculo",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["paciente_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["profissional_id"], ["profissionais.usuario_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pacientes_profissionais")
    op.drop_table("imagens")
    op.drop_table("profissionais")
    op.drop_table("diagnosticos")
    op.drop_table("conteudos_diagnostico")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_classificacoes_diagnostico_codigo"), table_name="classificacoes_diagnostico"
    )
    op.drop_table("classificacoes_diagnostico")
    # ### end Alembic commands ###
