"""cria tabela dicas

Revision ID: b4c99c48b0f2
Revises: 652cbc54920d
Create Date: 2026-09-11 20:19:42.431135

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b4c99c48b0f2"
down_revision: str | None = "652cbc54920d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dicas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("conteudo", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # A e7c1d2a3b4f5 apaga `dicas` (substituída por `conteudos`) e não a recria
    # no downgrade; por isso a tabela pode já não existir aqui.
    op.execute(sa.text("DROP TABLE IF EXISTS dicas"))
    # ### end Alembic commands ###
